# === Makefile.linux ===

CC = x86_64-elf-gcc
AS = nasm
LD = x86_64-elf-ld

CFLAGS = -ffreestanding -O2 -Wall -Wextra \
         -fno-builtin \
         -fno-stack-protector \
         -mno-red-zone \
         -mno-sse -mno-mmx -mno-sse2 \
         -fno-omit-frame-pointer \
         -Ikernel/include

LDFLAGS = -T linker.ld

C_SOURCES = $(shell find kernel -name "*.c")
C_OBJECTS = $(C_SOURCES:.c=.o)

all: kernel.bin iso

kernel.bin: boot.o $(C_OBJECTS)
	$(LD) $(LDFLAGS) boot.o $(C_OBJECTS) -o kernel.bin

boot.o:
	$(AS) -f elf64 boot/boot.asm -o boot.o

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

iso: kernel.bin
	mkdir -p iso/boot/grub
	cp kernel.bin iso/boot/
	cp grub.cfg iso/boot/grub/
	grub-mkrescue -o myos.iso iso

run: iso
	qemu-system-x86_64 -cdrom myos.iso
#qemu-system-x86_64 -bios /usr/share/OVMF/OVMF_CODE.fd -cdrom myos.iso
#qemu-system-x86_64 -M pc -m 512 -cdrom myos.iso

clean:
	find . -name "*.o" -delete
	rm -rf iso kernel.bin myos.iso

# === Makefile.linux ===